In [1]:
import torch 
from torch import nn  

In [2]:
inp_tensor = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)

print(inp_tensor)
print(target)

tensor([[-0.5957, -0.7001, -0.4951,  0.0043, -0.6051],
        [ 0.9539, -0.7690, -1.5705, -1.2382, -0.3925],
        [-0.2700,  0.5447,  0.8882,  1.4334, -1.8625]], requires_grad=True)
tensor([0, 1, 4])


In [6]:
inp_tensor = torch.randn(3, 5, requires_grad=True)
target = torch.argmax(inp_tensor, axis=1)

In [10]:
print(inp_tensor, target, m(inp_tensor))

tensor([[ 0.9394,  0.0797,  0.4177, -0.2117, -0.7536],
        [-0.0100, -1.8970,  0.7799,  0.7393,  2.9304],
        [-0.4623, -0.1115,  0.4278,  1.8050, -0.9050]], requires_grad=True) tensor([0, 4, 3]) tensor([[0.3973, 0.1682, 0.2358, 0.1257, 0.0731],
        [0.0410, 0.0062, 0.0903, 0.0867, 0.7758],
        [0.0660, 0.0937, 0.1607, 0.6371, 0.0424]], grad_fn=<SoftmaxBackward0>)


In [9]:
cc = nn.CrossEntropyLoss()
m = nn.Softmax(dim=1)
cc_error = cc(m(inp_tensor), target)
cc_error

tensor(1.2332, grad_fn=<NllLossBackward0>)

In [47]:
output = torch.Tensor([[1, 0, 0, 0, 0],
                       [0, 0, 0, 1, 0],
                       [0, 0, 0, 0, 1]])
target = torch.Tensor([0, 3, 4]).type(torch.long)

In [28]:
cc(output, target)

tensor(0.9108)

In [24]:
m(output)

tensor([[0.4046, 0.1488, 0.1488, 0.1488, 0.1488],
        [0.1488, 0.1488, 0.1488, 0.4046, 0.1488],
        [0.1488, 0.1488, 0.1488, 0.1488, 0.4046]])

In [38]:
cc(output, output)

tensor(0.9048)

In [30]:
ls = nn.LogSoftmax(dim=1)

In [31]:
nll = nn.NLLLoss()

In [35]:
ls(output)

tensor([[-0.9048, -1.9048, -1.9048, -1.9048, -1.9048],
        [-1.9048, -1.9048, -1.9048, -0.9048, -1.9048],
        [-1.9048, -1.9048, -1.9048, -1.9048, -0.9048]])

In [37]:
nll(ls(output), target)

tensor(0.9048)

In [48]:
class CategoricalCrossEntropyLoss(nn.Module):
    def __init__(self):
        super(CategoricalCrossEntropyLoss, self).__init__()

    def forward(self, y_hat, y):
        return nn.NLLLoss()(torch.log(y_hat), torch.argmax(y, dim=1))

In [49]:
ccee = CategoricalCrossEntropyLoss()
ccee(output, output)

tensor(0.)

In [52]:
class SparseCategoricalCrossEntropyLoss(nn.Module):
    def __init__(self):
        super(SparseCategoricalCrossEntropyLoss, self).__init__()

    def forward(self, y_hat, y):
        return nn.NLLLoss()(torch.log(y_hat), y)

In [53]:
scee = SparseCategoricalCrossEntropyLoss()

In [55]:
sample_inp = torch.Tensor([[0.9, 0.1, 0, 0, 0],
                       [0.1, 0.2, 0.1, 0.6, 0],
                       [0, 0, 0.3, 0.6, 0.1]])

In [56]:
scee(sample_inp, target)

tensor(0.9729)

In [41]:
import tensorflow as tf

In [42]:
y_true = [[0, 1, 0], [0, 0, 1]]
y_pred = [[0.01, 0.99, 0.0], [0.0, 0.01, 0.99]]
# Using 'auto'/'sum_over_batch_size' reduction type.
cce = tf.keras.losses.CategoricalCrossentropy()
cce(y_true, y_pred).numpy()


0.010050327

In [44]:
output = [[1.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 1.0]]
cce(output, output).numpy()

1.192093e-07